language: zh-CN
server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/spring_boot
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
    
#自定义参数配置
com:
   neo:
      title: 自定义参数标题
      description: 自定义参数描述
